server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

    # 最小线程数，防止突发激增的请求
    min-spare-threads: 200
    # 最大连接数 可以接收的连接数上限
    max-connections: 8192
    # 最大线程数 注意每一个线程创建时会分配1M的线程栈
    max-threads: 512
    # 最大等待数 超过这个长度tomcat直接拒绝服务
    # tomcat同一时间能够承受的最大连接是max-connections+accept-count?
    accept-count: 128

    # 线程没连接后3秒断开
    connection-timeout: 3s

#    # tomcat日志
#    accesslog:
#      buffered: false # 开关
#      file-date-format: .yyyy-MM-dd
#      pattern: common
#      prefix: myBlogTomcat
#      rename-on-rotate: false
#      request-attributes-enabled: false
#      rotate: true
#      suffix: .log
#      enabled: true
#      directory: D:\Code\blog\logs
#      encoding: UTF-8